[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#E8322B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFF3DA"
textColor = "#101010"
